### ISSUE TITLE
Missing (german) translations in SDK 1.12

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#1011]
In SDK 1.12 (at least) the german label translations for 

- ND-ProcedurePlacePerformance
- ND-ExclusionGroundsSource
- ND-SelectionCriteriaSource
- GR-FSR-Measures
- GR-Lot-EUFunds

are missing or incorrectly linked.

**Comment by YvesJo** [comment]
Hi,
You're request has reached the helpdesk and will be addressed.
KR

**Comment by GarrusMD** [comment]
I would like to add that the field BT-821-Lot is currently translated as ‘Quelle der Auswahlkriterien’, better would be ‘Quelle der Eignungskriterien’.

**Comment by YvesJo** [comment]
Already fixed with SDK 1.13. Will get backported.
