### ISSUE TITLE
Question regarding ElectronicMail regex

### ISSUE THREAD

**Issue by mdewinne** [OP-TED/eForms-SDK#1019]
We noticed that the current regular expression for validating e-mail addresses ([as used for example in fields.json](https://github.com/OP-TED/eForms-SDK/blob/b8dceadec82dbcf900d661935bce3c62d9aa6bb4/fields/fields.json#L24233)) contains the html character code `&amp;` in the character group right before the _@_. 

Is there a particular reason why the regex is formulated this way and not by using the character _&_ as such?

We try to align our platform as much as possible with the eForms standard, but noticed that said regex would - in its unaltered form - allow incorrect e-mail addresses containing a semicolon, as can be observed here:
https://regex101.com/r/5qh1ZO/1

But even within the SDK framework, we think that there might be an inconsistency between fields.json and schematron validation. Our front-end notice editor (which shows inline validation based on fields.json) accepts the addresses with a semicolon, only to see them refused afterwards by the schematron, when saving and validating the notice.

**Comment by bertrand-lorentz** [comment]
The regex is used in the schematron files, where the character "&" must be escaped as "&amp;".
But it is indeed incorrect to have it escaped in fields.json.

We'll look into resolving this issue, so that the regex is fully correct in fields.json.

**Comment by bertrand-lorentz** [comment]
This will be corrected in SDK 1.13.0 (see linked commit above).
Please note that the pattern to validate URL is also affected: it contained `&amp;`, but also `&quot;`, which will be replaced by `\"` (the correct escaping for JSON).
