### ISSUE TITLE
BT-706-UBO pdf generation problem

### ISSUE THREAD

**Issue by tompeeszter** [OP-TED/eForms-SDK#1030]
We have the following issue:
If there is more than one **BT-706 Winner Owner Nationality** given for one UBO we recive the following response in case of tryring to generate TED pdf: 
_"status":500,"error":"Internal Server Error","path":"/api/v2/notices/render"_
We use SDK 1.11.1
The xml has passed both the schematron and xml validations. I'm sending you an xml example.
[UBO_Nat_ID.txt](https://github.com/user-attachments/files/17211225/UBO_Nat_ID.txt)

It wasn't a problem in SDK 1.7.

We noticed if there is only one BT-706 Winner Owner Nationality or one UBO the pdf generation is OK but on the other hand there is a problem with the visualisation: 
![image](https://github.com/user-attachments/assets/740748bc-2bcf-4759-82f3-caa9ddc62c5b)
According to 29.efx file 'eforms-country' codelist is used but 'eforms-country' codelist doesn't exists in SDK 1.11.1.
_{ND-OrganizationUboReference[some text:$ubonationality in (for text:$orgid in OPT-200-Organization-Company, text:$uboid in OPT-302-Organization[OPT-200-Organization-Company == $orgid] return BT-706-UBO[OPT-202-UBO == $uboid]) satisfies $ubonationality != '']} #{field|name|BT-706-UBO}: #{code|name|${for text:$orgid1 in OPT-200-Organization-Company, text:$uboid1 in OPT-302-Organization[OPT-200-Organization-Company == $orgid1] return concat('eforms-country.', BT-706-UBO[OPT-202-UBO == $uboid1])}} // Beneficial Owner Nationality_

Could you please investigate this issue?
Thanks in advance!

**Comment by bertrand-lorentz** [comment]
The incorrect display when the is one nationality a problem introduced in SDK 1.11.0: we removed the codelist "eforms-country" (replaced by "country") but the view templates were not updated accordingly.
This will be corrected in SDK 1.13.0, and the correction will then be applied to older SDK versions (in your case there will be a vesion 1.11.2).

We'll check that the error you indicate when there is more that one nationality for an UBO is also corrected by this, or if it needs another correction.

**Comment by tompeeszter** [comment]
Thanks for your rapid answer!

**Comment by bertrand-lorentz** [comment]
The error when there is more that one nationality for an UBO will also be corrected in SDK 1.13.0, and then backported to older versions.

There's no precise timeline yet for the next round of patch versions (with 1.11.2), but it will probably be at least a few weeks after the release of version 1.13.0, which is currently foreseen for the end of October/early November.
