### ISSUE TITLE
Procedure missing for PIN CFC

### ISSUE THREAD

**Issue by MiraRatajczak** [OP-TED/eForms-SDK#1065]
We have noticed in the sdk 1.13 release candidate 2 in the code list procurement_procedure_type for sub notice type 10, 11, 12, 13 that the procedures neg-w-call is missing. We have checked the directives and it seems to be foreseen (cf. dir 24 art. 48 $2, dir 25 art. 67 $2). Can this be included in the sdk 1.13, in Belgium we have active publications using this procedure in PIN CFC?

**Comment by YvesJo** [comment]
Hi,
We will look closer into that and will get back to you.
KR

**Comment by YvesJo** [comment]
After clarification, decision has been made to have it added.
