### ISSUE TITLE
[SDK 1.13 RC2] Cannot map BT-1311 in subcontracting form (22)

### ISSUE THREAD

**Issue by rjvdhulst** [OP-TED/eForms-SDK#1066]
While testing the release candidate for SDK1.13 I ran into an issue with the subcontracting form. 

It is impossible to map BT-1311, because the schematron (BR-BT-01311-0112) validation requires BT-105 to be present for validation.

**Comment by YvesJo** [comment]
Hi,
Not sure I understand what is meant with "It is impossible to map BT-1311".
BT-1311 is only allowed for multi stages procedures and the referenced rule requires BT-105 to be specified so that data consistency may be ensured.
Similarly, BT-131 is only allowed for single stage procedures.

**Comment by rjvdhulst** [comment]
Hi,
BT-105 is not present in form 22.
