### ISSUE TITLE
Contents of BT-745 lot are not displayed on TED

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#1088]
One of our users pointed out that the content of BT-745-Lot is not displayed on TED.

Here is an example: https://ted.europa.eu/de/notice/-/detail/746430-2024

As you can see in the XML, the BT 8x is in the XML (once for each lot) but it is not displayed in the interface.

**Comment by pdonohoe** [comment]
As this is not an issue with the eForms SDK, please raise this issue with the OP TED HELPDESK (OP-TED-HELPDESK@publications.europa.eu).

**Comment by GarrusMD** [comment]
But doesn't TED use the SDK to display the notices?

**Comment by pdonohoe** [comment]
No it doesn't. The Viewer APIs use the EFX in the SDK to display the notice, but the TED website uses different code. In this case, the bug affects both viewers, so it has a wider scope. We prefer that all display issues are routed via the OP TED Helpdesk, so we can involve the appropriate groups.
