### ISSUE TITLE
Fix missing parent-child relations in the cpv.gc file

### ISSUE THREAD

**Issue by skyazid** [OP-TED/eForms-SDK#1089]
During the validation of parent-child relations in the cpv.gc file, several child elements were identified without corresponding parent elements.

++++++++++++++++++
code : 35611800
parentCode : 35610000
++++++++++++++++++
code : 38527400
parentCode : 38520000
++++++++++++++++++
code : 35611700
parentCode : 35610000
++++++++++++++++++
code : 60112000
parentCode : 60100000
++++++++++++++++++
code : 44115310
parentCode : 44115000
++++++++++++++++++
code : 35811200
parentCode : 35810000
++++++++++++++++++
code : 35612100
parentCode : 35610000
++++++++++++++++++
code : 34511100
parentCode : 34510000
++++++++++++++++++
code : 35811100
parentCode : 35810000
++++++++++++++++++
code : 35612300
parentCode : 35610000
++++++++++++++++++
code : 35811300
parentCode : 35810000
++++++++++++++++++
code : 35612200
parentCode : 35610000
++++++++++++++++++
code : 42924700
parentCode : 42920000
++++++++++++++++++
code : 35611200
parentCode : 35610000
++++++++++++++++++
code : 35612500
parentCode : 35610000
++++++++++++++++++
code : 35612400
parentCode : 35610000
++++++++++++++++++
code : 35611100
parentCode : 35610000
++++++++++++++++++
code : 35611400
parentCode : 35610000
++++++++++++++++++
code : 44613110
parentCode : 44613000
++++++++++++++++++
code : 38527100
parentCode : 38520000
++++++++++++++++++
code : 42924200
parentCode : 42920000
++++++++++++++++++
code : 35611300
parentCode : 35610000
++++++++++++++++++
code : 38527200
parentCode : 38520000
++++++++++++++++++
code : 35611600
parentCode : 35610000
++++++++++++++++++
code : 42924300
parentCode : 42920000
++++++++++++++++++
code : 38527300
parentCode : 38520000
++++++++++++++++++
code : 35611500
parentCode : 35610000
++++++++++++++++++
code : 39254000
parentCode : 39200000
++++++++++++++++++

A corrected version of the cpv.gc file is attached to this issue with all necessary fixes applied.

[cpv.zip](https://github.com/user-attachments/files/18108194/cpv.zip)

**Comment by rouschr** [comment]
Hello,

we had found such a hierarchy issue in the past, which version of the SDK are you using?

**Comment by doc-yh** [comment]
Hello,

We use the latest version 1.13

**Comment by rouschr** [comment]
From what I remember about this topic, we had reported problems to the maintainers of CPV or those that generate the CPV rdf files. We are parsing the rdf of CPV in which these relations were missing.
It is possible that they did the fix in the mean time (maybe in June or July), however the version of CPV itself did not change and our synchronization is based on the codelist version. Normally when a codelist changes the version should change for caching logic or quick version comparison purposes.

I can investigate this on my side by putting this topic into my current sprint, it is possible the fixes would end up in SDK 1.14 if they fixed it. In the worst case we could also consider just using your version as a patch until they provide a fixed rdf as the cpv itself is not too different from the original 2008 version.
