### ISSUE TITLE
Namespace of BT-7220-Lot & BT-722-Contract

### ISSUE THREAD

**Issue by fpoort** [OP-TED/eForms-SDK#119]
Their appears to be problem with the namespaces of the fields "BT-7220-Lot" and "BT-722-Contract". The fields.json shows the following:

BT-7220-Lot "efac:Funding/efbc:FundingProgramCode"
BT-722-Contract "efac:Funding/efbc:FundingProgramCode"

The actual object FundingProgramCode is not available in the efbc namespace, but appears to be available in the cbc namespace.

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.

This is indeed a mistake in the XPaths for those 2 fields. This will be corrected in the next version of the SDK.

**Comment by bertrand-lorentz** [comment]
This is fixed in SDK 1.2.0.
