### ISSUE TITLE
Question about UBL-CommonAggregateComponents-2.3 XSD "PartyType" is self-referencing own type 

### ISSUE THREAD

**Issue by Havunen** [OP-TED/eForms-SDK#208]
Hi,

In UBL-CommonAggregateComponents-2.3 XSD

https://github.com/OP-TED/eForms-SDK/blob/230557b69cb5e0ff30794b0113132dc2418675c4/schemas/common/UBL-CommonAggregateComponents-2.3.xsd#L3392-L3418

PartyType -type contains property cac:AgentParty which has type of PartyType and references back to iself: 
https://github.com/OP-TED/eForms-SDK/blob/230557b69cb5e0ff30794b0113132dc2418675c4/schemas/common/UBL-CommonAggregateComponents-2.3.xsd#L58

Is this intentional ?

**Comment by Havunen** [comment]
Also types shipmentType and deliveryType are referencing each other:

![image](https://user-images.githubusercontent.com/2021355/201640035-9a39750f-e93d-442b-b9e6-d75334ac9eb0.png)

**Comment by klakegg** [comment]
This is intentional and is copied from UBL. Please see the official UBL distribution and send your comments to the official [UBL comments list](https://www.oasis-open.org/committees/comments/index.php?wg_abbrev=ubl) if you have any further UBL specific findings you want to discuss.

**Comment by bertrand-lorentz** [comment]
This is the same topic as in issue #207, please also see my answer there.

As this is not an issue in the SDK, I'm closing this. Feel free to provide further feedback and share your experience in the ["Discussions" forum](https://github.com/OP-TED/eForms-SDK/discussions)
