### ISSUE TITLE
OriginatorCustomerParty is not consistent accross different notice types

### ISSUE THREAD

**Issue by Havunen** [OP-TED/eForms-SDK#212]
In PrioInformationNotice XSD `cac:OriginatorCustomerParty` is defined as a list of OriginatorCustomerParty types.
( ref: https://github.com/OP-TED/eForms-SDK/blob/develop/schemas/maindoc/UBL-PriorInformationNotice-2.3.xsd#L53-L55 )
In ContractNotice XSD its also defined as list of OriginatorCustomerParty types.
(ref: https://github.com/OP-TED/eForms-SDK/blob/develop/schemas/maindoc/UBL-ContractNotice-2.3.xsd#L52-L54)

But in contract award notice type it is defined as single type "maxOccurs=1"
(ref: https://github.com/OP-TED/eForms-SDK/blob/develop/schemas/maindoc/UBL-ContractAwardNotice-2.3.xsd#L58)

Is this intentional?

**Comment by bertrand-lorentz** [comment]
The various UBL-*.xsd files are coming directly from the UBL 2.3 standard; as published by OASIS: https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=ubl
So any question about the design choices those files reflect should be directed to the UBL committee (info at the link above).

In addition, the element `cac:OriginatorCustomerParty` is not used for any field in eForms.

So I'm closing this, as it is not directly related to the eForms SDK.
