### ISSUE TITLE
group_nl.xml translation error

### ISSUE THREAD

**Issue by mdewinne** [OP-TED/eForms-SDK#215]
See [group_nl.xml](https://github.com/OP-TED/eForms-SDK/blob/develop/translations/group_nl.xml)
Line 79: <entry key="group|name|GR-LotResult-Parties">Feesten</entry>

The correct translation for "parties" would be "Partijen", not "Feesten" (which means "feasts"/"fests", "celebrations")

**Comment by bertrand-lorentz** [comment]
Thank you for your feedback.
This will be corrected in the next version of the SDK.
Please note some translations have been initially created via machine translations, and are currently being reviewed by our translation teams.

**Comment by bertrand-lorentz** [comment]
This has been resolved in SDK 1.4.0.
