### ISSUE TITLE
Missing colons in efx

### ISSUE THREAD

**Issue by jonatanprins** [OP-TED/eForms-SDK#263]
We noticed a few lines which look like they are missing a ':'.

For example in 29.efx, section 6:

![afbeelding](https://user-images.githubusercontent.com/1318488/205869003-3bdfeb4c-44f9-427e-b27b-f87dc0006b81.png)

SDK version 1.4 used.

**Comment by pdonohoe** [comment]
Thanks for spotting these. They will be fixed with SDK version 1.6
