### ISSUE TITLE
BT-661 (lot) fields.json and schema are in conflict

### ISSUE THREAD

**Issue by Havunen** [OP-TED/eForms-SDK#266]
BT-661 (lot) is defined as indicator type in the fields.json

ref: https://github.com/OP-TED/eForms-SDK/blob/develop/fields/fields.json#L16670-L16690

But in the schema this property is defined as TextType array

https://github.com/OP-TED/eForms-SDK/blob/develop/schemas/maindoc/UBL-ContractAwardNotice-2.3.xsd#L61
https://github.com/OP-TED/eForms-SDK/blob/develop/schemas/common/UBL-CommonAggregateComponents-2.3.xsd#L4999-L5001
https://github.com/OP-TED/eForms-SDK/blob/develop/schemas/common/UBL-CommonAggregateComponents-2.3.xsd#L2221 (array  minOccurs="0" maxOccurs="unbounded" )
 
and finally limit description is defined as text type: 
https://github.com/OP-TED/eForms-SDK/blob/develop/schemas/common/UBL-CommonBasicComponents-2.3.xsd#L3551-L3555

We were expecting this field to be indicator type in XSD

**Comment by Havunen** [comment]
Also BT-14 is defined as indicator but is referencing text type

https://github.com/OP-TED/eForms-SDK/blob/develop/fields/fields.json#L3510-L3529

shouldn't this field be code type?

**Comment by Havunen** [comment]
I found out there is document describing this weird behavior: https://simap.ted.europa.eu/documents/10184/320101/eForms+regulation+vs+Schemas_2/8209153c-9541-4672-9c89-25891137744c

It would be nice to have these documented to the SDK somehow

**Comment by YvesJo** [comment]
There are indeed differences between the Implementing Regulation and the UBL Standard; these have been addressed and integrated into the SDK while considering the requirements imposed by both.
Information also exists in the documentation, if you however consider that some information should be added to the SDK, I then recommend that you preferably develop and share this **idea** in the **discussion** channel. Clearly stating the expectations (e.g. format, purpose ...) would increase the probability to have it considered and integrated.
I also close this (non-)issue.
KR
