### ISSUE TITLE
listName attributes missing from fields.json ?

### ISSUE THREAD

**Issue by Havunen** [OP-TED/eForms-SDK#269]
Based on the documentation and documentation example from here:
https://docs.ted.europa.eu/eforms/latest/codelists/index.html#_codelists_in_eforms_notice_xml

ProcurementTypeCode should have list name of "contract-nature" there are **many fields** in fields.json which do not have listname attribute set in the path, but they have code list defined as a value.
Even the example shown in the documentation is missing attribute name? 

one example: 
https://github.com/OP-TED/eForms-SDK/blob/develop/fields/fields.json#L11433-L11485

Schema:
https://github.com/OP-TED/eForms-SDK/blob/230557b69cb5e0ff30794b0113132dc2418675c4/schemas/common/UBL-CommonAggregateComponents-2.3.xsd#L3773-L3783

How can we programmically detect what list name should be used in each field?

Eforms code list example:
https://github.com/OP-TED/eForms-SDK/blob/develop/codelists/contract-nature_eforms-contract-nature.gc#L6

Now those eforms code lists have name "eforms-something-foo-bar" but the listName in the data should be "something-foo-bar"? Does this rule apply to all eforms specific code lists?

Could there be a field in the config that tells the name of the code list to be used in the data? Or does the data have different listName even if the value is selected from the same code list per schema location?

**Comment by YvesJo** [comment]
Hi,
From the referred example, we may extract the following lines.

```
{
    "id" : "BT-23-Part",
    "parentNodeId" : "ND-PartProcurementScope",
    "name" : "Main Nature",
    "btId" : "BT-23",
    "xpathAbsolute" : "/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']/cac:ProcurementProject/cbc:ProcurementTypeCode[@listName='contract-nature']",
    "xpathRelative" : "cbc:ProcurementTypeCode[@listName='contract-nature']",
    "type" : "code",
    "legalType" : "CODE",
   
    --- removed lines ---

    "codeList" : {
      "value" : {
        "id" : "eforms-contract-nature",
        "type" : "flat",
        "parentId" : "contract-nature"
      },
      "severity" : "ERROR"
    },
```
For "codelist", "id" is referring to the identifier of the codelist to be used for value selection and "parentId" to the listName attribute value to report when the listName attribute exists (i.e. element of type code in the XSD) and the value shall defer from the one of "id".
KR

**Comment by Havunen** [comment]
Ok good to know. 

And this rule

> For "codelist", "id" is referring to the identifier of the codelist to be used for value selection and "parentId" to the listName attribute value to report when the listName attribute exist

Applies universally to all fields in the field.json right?

**Comment by YvesJo** [comment]
Do not miss the end of the sentence:

> For "codelist", "id" is referring to the identifier of the codelist to be used for value selection and "parentId" to the listName attribute value to report when the listName attribute exists ... **and the value shall defer from the one of "id"**.

meaning that, when it exists, the listName attribute shall have:
- the "id" value, or
- when "parentId" is specified in the json file, the "parentId" value.

The rule applies everywhere except for the few cases where the listName attribute is associated to a field (BT-03-notice, BT-26(a)-Lot, BT-26(a)-Part, BT-26(a)-Procedure).

**Comment by Havunen** [comment]
Ok, makes sense now. Thank you
