### ISSUE TITLE
XPaths in fields.json

### ISSUE THREAD

**Issue by fpoort** [OP-TED/eForms-SDK#27]
We are looking into a meta data driven implementation of eForms. We came across some fields which appear to be in a different location in the XSD then the fields.json says they should be. 

Are we using the field.json in the wrong way?

I've added some examples below, which occur in noticesubtypes 23 & 24.

```
Field id: BT-46-Lot
Absolute Path: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:Prize/cac:TechnicalCommitteePerson/cbc:FamilyName
Actual Path in the XSD: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:TechnicalCommitteePerson/cbc:FamilyName

Field id: ND-334
Absolute Path: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:EconomicOperatorShortList
Actual Path in the XSD: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:EconomicOperatorShortList
```

**Comment by rousso** [comment]
Hi @fpoort,

Thank you for reporting this. 

Indeed the information in the SDK is incorrect for these two fields. 
The fix will be available in the next release of the SDK. 
If you spot any other inconsistencies please report them and we will address them in the next release.

Regards,
Yannis
