### ISSUE TITLE
Missing English translations in the code list innovative-acquisition

### ISSUE THREAD

**Issue by arturasliepys** [OP-TED/eForms-SDK#280]
In the code list innovative-acquisition there are missing English translations for codes **prod-innov** and **proc-innov**

<Value ColumnRef="Name">
  <SimpleValue/>
</Value>

source - https://github.com/OP-TED/eForms-SDK/blob/develop/codelists/innovative-acquisition.gc

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.
the English translations were indeed missing in the source we use for this code list: the Genericode file from https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/innovative-acquisition
But the labels are available in other formats, so we've added them.
This will be included in a next version of the SDK.

**Comment by bertrand-lorentz** [comment]
This was fixed in version 1.5.1 of the SDK.
