### ISSUE TITLE
BT-23-Lot - fields.json and notice-type json are in conflict

### ISSUE THREAD

**Issue by cgiehl** [OP-TED/eForms-SDK#286]
BT-23-Lot is defined as code type in the fields.json (codelist "eforms-contract-nature")

ref: https://github.com/OP-TED/eForms-SDK/blob/develop/fields/fields.json

In some notice-type json files the display type of this property is defined as radio

https://github.com/OP-TED/eForms-SDK/blob/develop/notice-types/16.json

The correct display type would be "COMBOBOX", as in BT-23-Procedure or BT-531-Lot

**Comment by bertrand-lorentz** [comment]
Radio buttons and combo boxes offer the same capability: select one value from a set of possible values.
So using one or the other is more of a design choice. But indeed, having the same info (BT-23-Procedure and BT-23-Lot) once as combo and once as radio buttons seems confusing.

**Comment by bertrand-lorentz** [comment]
This issue has been resolved in version 1.6.0 of the SDK.
