### ISSUE TITLE
Empty location in example SVRL reports

### ISSUE THREAD

**Issue by openegi** [OP-TED/eForms-SDK#289]
Some SVRL example reports contain `failed-assert`s with attribute `location=""`.

## Context

eForms-SDK v.1.5.0

## Details

In some SVRL example reports (`/examples/reports/`), a few `failed-assert` tags have attribute `location=""` instead of an XPath expression that points to the error in the notice. I've listed:
* `INVALID_can_24_stage-1.svrl`, line 582 and 603
* `INVALID_cn_24_stage-1.svrl`, line 621 and 642
* `INVALID_pin-buyer_stage-1.svrl`, line 294
* `INVALID_pin-only_stage-1.svrl`, line 346 and 367

For example, in `INVALID_can_24_stage-1.svrl contains

```xml
   <svrl:failed-assert id="BR-BT-00026-0605"
                       location=""
                       role="ERROR"
                       test="normalize-space(.) = ('cpv')">
      <svrl:text>rule|text|BR-BT-00026-0605</svrl:text>
   </svrl:failed-assert>
```

```xml
   <svrl:failed-assert id="BR-BT-00026-0609"
                       location=""
                       role="ERROR"
                       test="normalize-space(.) = ('cpv')">
      <svrl:text>rule|text|BR-BT-00026-0609</svrl:text>
   </svrl:failed-assert>
```

The triggered rules are `BR-BT-00026-0605`, `BR-BT-00026-0607`, `BR-BT-00026-0609`.

## Expected value

In `INVALID_can_24_stage-1.svrl`:

```xml
   <svrl:failed-assert id="BR-BT-00026-0605"
                       location="/ContractAwardNotice/cac:ProcurementProject/cac:MainCommodityClassification/cbc:ItemClassificationCode/@listName"
                       role="ERROR"
                       test="normalize-space(.) = ('cpv')">
      <svrl:text>rule|text|BR-BT-00026-0605</svrl:text>
   </svrl:failed-assert>
```

```xml
   <svrl:failed-assert id="BR-BT-00026-0609"
                       location="/ContractAwardNotice/cac:ProcurementProjectLot/cac:ProcurementProject/cac:MainCommodityClassification/cbc:ItemClassificationCode/@listName"
                       role="ERROR"
                       test="normalize-space(.) = ('cpv')">
      <svrl:text>rule|text|BR-BT-00026-0609</svrl:text>
   </svrl:failed-assert>
```

**Comment by bertrand-lorentz** [comment]
This has been resolved in SDK 1.8.0, the validation reports are produced with the same Schematron implementation as CVS.
