### ISSUE TITLE
Exclusion-ground code list used by CVS seems to be wrong

### ISSUE THREAD

**Issue by alexmohora** [OP-TED/eForms-SDK#331]
I have a notice (sub type 16) generated with Notice2, exported as XML, edited to be valid against XSD. The response from CVS (preview environment) for this notice contains also the validation BR-BT-00067-0104 with error "BT-67(a)-Procedure must contain one of the values of the code list exclusion-ground". The problem is that the code list used to test is not the correct one.

The correct code list I assume is this one: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/criterion

But the TEST code list is:
normalize-space(.) = ('CRITERION.EXCLUSION.BUSINESS.ACTIVITIES_SUSPENDED', 'CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY', 'CRITERION.EXCLUSION.BUSINESS.BANKRUPTCY_ANALOGOUS', 'CRITERION.EXCLUSION.BUSINESS.CREDITORS_ARRANGEMENT', 'CRITERION.EXCLUSION.BUSINESS.INSOLVENCY', 'CRITERION.EXCLUSION.BUSINESS.LIQUIDATOR_ADMINISTERED', 'CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.EARLY_TERMINATION', 'CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.MISINTERPRETATION', 'CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.PROCEDURE_PARTICIPATION', 'CRITERION.EXCLUSION.CONFLICT_OF_INTEREST.PROCEDURE_PREPARATION', 'CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_SOCIAL_SECURITY', 'CRITERION.EXCLUSION.CONTRIBUTIONS.PAYMENT_OF_TAXES', 'CRITERION.EXCLUSION.CONVICTIONS.CHILD_LABOUR-HUMAN_TRAFFICKING', 'CRITERION.EXCLUSION.CONVICTIONS.CORRUPTION', 'CRITERION.EXCLUSION.CONVICTIONS.FRAUD', 'CRITERION.EXCLUSION.CONVICTIONS.MONEY_LAUNDERING', 'CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION', 'CRITERION.EXCLUSION.CONVICTIONS.TERRORIST_OFFENCES', 'CRITERION.EXCLUSION.MISCONDUCT.MARKET_DISTORTION', 'CRITERION.EXCLUSION.MISCONDUCT.MC_PROFESSIONAL', 'CRITERION.EXCLUSION.NATIONAL.OTHER', 'CRITERION.EXCLUSION.SOCIAL.ENVIRONMENTAL_LAW', 'CRITERION.EXCLUSION.SOCIAL.LABOUR_LAW', 'CRITERION.EXCLUSION.SOCIAL.SOCIAL_LAW')
[response_1675434226004.zip](https://github.com/OP-TED/eForms-SDK/files/10720438/response_1675434226004.zip)

**Comment by bertrand-lorentz** [comment]
Based on the fact that the test indicated contains "CRITERION.EXCLUSION...", it seems to indicated that the notice was validated using rules from SDK 1.0 or 1.1.
The content of the corresponding codelist was updated in SDK 1.2 with codes in lower case, and the validation was updated accordingly.

What are the parameters you've sent in your request to CVS ?
Please note that CVS will by default use the rules corresponding to the version indicated in the notice in the element  `<cbc:CustomizationID>`, which is probably what you want.
If you override this by using the "eFormsSdkVersion", CVS will use the rules corresponding to the version indicated in this parameter.

**Comment by alexmohora** [comment]
Thank you for clarification! Indeed I thought that the value in <cbc:CustomizationID> is enough for indicating the SDK version. Didn't imagine there is another parameter in request for the same thing and I didn't notice it in the swagger.

I tried again and it was way better!

**Comment by bertrand-lorentz** [comment]
As this is not an issue with the SDK itself, I'm closing this.
