### ISSUE TITLE
inconsistant schematron rules concerning BT-10

### ISSUE THREAD

**Issue by ChristianeCPeters** [OP-TED/eForms-SDK#346]
according to CEllex, BT-10 is CM conditionally mandatory,

the schematron rules for the condition are inconsistant: 

Example Notice type 2 but occurs for several notice types
Line 595: 
<entry key="rule|text|BR-BT-00010-0005">BT-10-Procedure-Buyer is **mandatory for a notice with subtype 2** under the condition: Buyer Legal Type (BT-11-Procedure-Buyer) is not "Body governed by public law", "Body governed by public law, controlled by a central government authority", "Body governed by public law, controlled by a local authority", "Body governed by public law, controlled by a regional authority", "Central government authority", "Defence contractor", "EU institution, body or agency", "European Institution/Agency or International Organisation", "Group of public authorities", "International organisation", "Local authority", "Organisation awarding a contract subsidised by a contracting authority", "Organisation awarding a contract subsidised by a central government authority", "Organisation awarding a contract subsidised by a local authority", "Organisation awarding a contract subsidised by a regional authority", "Regional authority" or "Regional or local authority"</entry>

line 639 same condition but "forbidden" as result
<entry key="rule|text|BR-BT-00010-0053">BT-10-Procedure-Buyer is **forbidden for a notice with subtype 2** under the condition: Buyer Legal Type (BT-11-Procedure-Buyer) is not "Body governed by public law", "Body governed by public law, controlled by a central government authority", "Body governed by public law, controlled by a local authority", "Body governed by public law, controlled by a regional authority", "Central government authority", "Defence contractor", "EU institution, body or agency", "European Institution/Agency or International Organisation", "Group of public authorities", "International organisation", "Local authority", "Organisation awarding a contract subsidised by a contracting authority", "Organisation awarding a contract subsidised by a central government authority", "Organisation awarding a contract subsidised by a local authority", "Organisation awarding a contract subsidised by a regional authority", "Regional authority" or "Regional or local authority"</entry>

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.

I assume that you are referring to the content of the file `rule_en.xml` in the `translation` folder. This file contains the English texts corresponding to the messages for validation rules.
The 2 messages you mention (`rule|text|BR-BT-00010-0005` and `rule|text|BR-BT-00010-0053`) are indeed contradictory. The condition of the "mandatory" rule should be negated.

Please note that those 2 messages correspond to rules that were removed in [SDK version 1.3.0](https://github.com/OP-TED/eForms-SDK/releases/tag/1.3.0). The message were not removed, but they are currently not used.
The implementation of the rule was correct, the error was just in the text of the message. When we bring back those rules we will ensure the messages are correct.

**Comment by bertrand-lorentz** [comment]
In the next version of the SDK (1.7.0), we are adding back a few "conditionally mandatory" rules, and the way the message are created was corrected, so any rules that is added back will have a correct message.

So I'm closing this issue.
