### ISSUE TITLE
Simplify management of schematron message translations

### ISSUE THREAD

**Issue by rkottmann** [OP-TED/eForms-SDK#35]
Currently 

You provide schmetron rules/asserts the following way:

```xml
<assert id="ND-GazetteReference-1" role="ERROR" test="count(cac:AdditionalDocumentReference) = 0">rule|message|ND-GazetteReference-1</assert>
````
and provide the translations in another files like `rule_${iso-lang}` 

A much simpler way and more easy to comprehend for schematron developers would be instead:

```xml
<assert id="ND-GazetteReference-1" role="ERROR" test="count(cac:AdditionalDocumentReference) = 0">The element cac:AdditionalDocumentReference is not allowed under /*</assert>
```
with default messages in English (especially for the ones who just want to use the Schematrons `as-is` )

Then you just need:
e.g. in `rule_fr.xml` an entry as follows:

```xml
<entry key="ND-GazetteReference-1">French translation is actually missing (another bug I guess)</entry>
```

where the `entry key` is the `id` of the schmetron rule. 

Advantages:

* There is at least one original message in schematron -> direct comprehension
*  hence a bug like not having a french translation gives developers at least an English message instead of a cryptic `rule|message|ND-GazetteReference-1`
* Your Schematrons are more usable out of the context of the SDK and not everyone has to always make the translation before being able to understand SVRL output. -> Added value

**Comment by bertrand-lorentz** [comment]
Thank you for the suggestion!

When we initially defined the way to handle translations, we didn't have the id attribute in the assert element, so we put the label identifier as content of the assert element.

Now that we have this id, what you suggest could be possible, so we will look into it.

**Comment by bertrand-lorentz** [comment]
After looking into this suggestion, we realized that:
- This would require a change in validation systems (ours and possibly others) that have already implemented the lookup based on the content of the assert element
- Adding the English messages would increase the size of schematron files, and the memory required to load them in a validation system, which are both quite large already

So we will not implement this for now, but in the future we will consider other solutions to make our Schematron rules more readable/usable for humans.

**Comment by rousso** [comment]
I am closing this as the proposed action will not be implemented.
Thank you @rkottmann, @bertrand-lorentz
