### ISSUE TITLE
fields.json schemeName incomplete 

### ISSUE THREAD

**Issue by karel-debrabandere-bosa-fgov-be** [OP-TED/eForms-SDK#365]
## Intro
The schemeName attribute was added to some fields in release 1.6.0

I notice that the attribute was only added to those fields that are the id field of an idScheme, instead of to all fields that would need a `"schemeName"="..."` attribute in the xml:

## `schemeName` attribute included in 1.6.0
- idScheme id field:
```
{
    "id" : "OPT-321-Tender",
    "type" : "id",
    "idScheme" : "TEN",
    "schemeName" : "tender",
}
```

## Some fields without schemeName that need it in the xml representation:
- `id-ref` fields:
```
{
    "id" : "BT-13714-Tender",
    "type" : "id-ref",
    "idSchemes" : [ "GLO", "LOT" ],
    // "schemeNames": [ "LotsGroup", "Lot" ]
}
```
- `Internal Identifier` fields: 
```
{
    "id" : "BT-22-Lot",
    "name" : "Internal Identifier",
    "type" : "id",
    // "schemeName": "InternalID"
}
```
- specific metadata fields:
```
{
    "id" : "BT-701-notice",
    // "schemeName": "notice-id"
}
```
```
{
    "id" : "OPP-010-notice",
    // "schemeName": "ojs-notice-id"
}
```
```
{
    "id" : "OPP-011-notice",
    // "schemeName": "ojs-id"
}
```

**Comment by rouschr** [comment]
In SDK 1.9 you will have extra information on attribute fields:
```
    "type" : "text",
    "attributeName" : "schemeName",
    "attributeOf" : "OPP-090-Procedure",
    "presetValue" : "ojs-notice-id",
...
```
On identifier you still have something like:
```
    "type" : "id",
    "attributes" : [ "OPT-316-Contract-Scheme" ],
    "idScheme" : "CON",
    "schemeName" : "contract",
```
