### ISSUE TITLE
BT-531-Lot is allowed in all forms, is it correct?

### ISSUE THREAD

**Issue by eduardsmirnov** [OP-TED/eForms-SDK#376]
Please answer my question in the previous discussion. Seems BT-531-Lot has incorrect visibility information.
### Discussed in https://github.com/OP-TED/eForms-SDK/discussions/257

<div type='discussions-op-text'>

<sup>Originally posted by **eduardsmirnov** December  2, 2022</sup>
All SDK versions, including the latest one (1.4.1) make the field BT-531-Part visible in all forms (missing forbidden condition).
Is it a bug or expected behavior? It leads to the duplicated field of "Additional nature of the contract". It is also the only field with a suffix "-PART" which is allowed in all forms.</div>

**Comment by YvesJo** [comment]
It is not an expected behavior and shall get fixed with the next release.

**Comment by bertrand-lorentz** [comment]
This was resolved in SDK 1.6.0.

Sorry we forgot to update this issue.
