### ISSUE TITLE
Should CalculationExpression (BT-543-Lot) ba a sibling to SubordinateAwardingCriterion or inside SubordinateAwardingCriterion?

### ISSUE THREAD

**Issue by sorliden** [OP-TED/eForms-SDK#378]
In [Procedure, Group of Lots, Lot & Part related information :: TED Developer Documentation](https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#awardCriteriaSection) CalculationExpression is a sibling to AwardCriteriaComplicatedLot.
![image](https://user-images.githubusercontent.com/43994636/225945393-4d44aec2-ece0-4695-b89e-3f87782d2168.png)
There are xml examples in the SDK that show both variants:
cn-social_24.xml
![image](https://user-images.githubusercontent.com/43994636/225945804-7b6dceed-f885-43de-9343-40e42732cc94.png)
can_24_minimal.xml
![image](https://user-images.githubusercontent.com/43994636/225945722-fa77a230-308e-460d-8eb6-6808ac7e46de.png)

**Comment by eduardsmirnov** [comment]
I would trust fields.json. It defines xpath as 
`"xpathAbsolute" : "/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cbc:CalculationExpression"`

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.

The example `cn-social_24.xml` was indeed incorrect. It will be corrected in the next version of the SDK (see linked commit).
