### ISSUE TITLE
Incorrect Placement of nodeId "ND-LotTenderingProcess" in NTDs

### ISSUE THREAD

**Issue by sbo2718** [OP-TED/eForms-SDK#386]
In 1.6.0 the group "GR-Lot-Purpose" received the nodeId "ND-LotTenderingProcess".

According to https://docs.ted.europa.eu/eforms/latest/notice-types/index.html my assumption is that all fields having this node as an ancestor should be a part of this group, but for some of the fields like BT-131(d)-Lot and BT-131(t)-Lot that is not the case.

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.

As indicated in the documentation page:

> There is no constraint on non-repeatable groups. An arbitrary number of intermediate, non-repeatable groups can be created to organize the notice fields in a more convenient way.

In this case, fields like BT-131(d)-Lot are in a different non-repeatable group than other fields that are also under the node "ND-LotTenderingProcess". But the closest repeatable parent is the same : GR-Lot.
So the notice type definition is still "aligned" with the XML structure: Both only allow one occurrence of BT-131(d)-Lot in a lot.

The association of a group to a node is *relevant for the structure* only for repeatable groups. We have added other associations to help relate the XML with the form shown to a user (in particular for validation messages), but they are not necessary from a structural perspective.

I'm closing this as it does not seem to be a problem in the SDK.
