### ISSUE TITLE
Options and renewals

### ISSUE THREAD

**Issue by MiraRatajczak** [OP-TED/eForms-SDK#390]
We noticed that fields BT-54 and BT-57 are not placed in the correct groups:
      BT-54 should be placed in group ND-OptionsDescription and not in GR-Lot-ContractExtension  
      BT-57 should be placed in group GR-Lot-ContractExtension and not in ND-OptionsDescription
And shouldn’t ND-OptionsDescription be at the same level as GR-Lot-ContractExtension, rather then being nested in the latter?
![2023-03-28_09h27_19](https://user-images.githubusercontent.com/40240070/228450005-7226e8a1-5573-458c-bc29-10dc5eb0f296.png)

**Comment by rouschr** [comment]
This has been fixed in 1.8 or earlier.
(Maybe we already discussed this outside of this issue, I am writing this so that the issue can be closed)
