### ISSUE TITLE
Publication flow seems to be paused

### ISSUE THREAD

**Issue by eduardsmirnov** [OP-TED/eForms-SDK#396]
The publication flow in TEST seems to be paused. My submitted notices are not published for 2 days. Could you confirm?

**Comment by eduardsmirnov** [comment]
this notice is waiting for a week to be published, is it only my issue?
35bfeb3d-78a4-49ed-a6af-4df88a501504-01

**Comment by ferrakaop** [comment]
In the Preview environment, it is possible for notices to get stuck in the back-end system (TED Monitor): they enter a technical workflow error and we don't manually acknowledge them to put them into Not Published status - so they stay indefinitely in Submitted.

For your specific notice, the error is that it links to a previous notice that hasn't been published and the system puts it in error as it cannot establish a link between the notices.

In future we will implement the CVS rule that checks that linked notices are have been Published but until then these back-end errors may happen. In any case, it's useful for eSender applications to check the links before submission (regardless of the CVS check) though I realise that this case was just a test that had a confusing outcome for you.

**Comment by bertrand-lorentz** [comment]
If you encounter an issue specific to one of our applications, in the "Preview" or "Production" environment, please contact the TED helpdesk at ted@publications.europa.eu
