### ISSUE TITLE
error in codelist-definition for BT-01-notice in fields.json

### ISSUE THREAD

**Issue by gabrieledall** [OP-TED/eForms-SDK#399]
The current codelist-definition for BT-01-notice is:

"codeList" : {
      "value" : {
        "id" : "eforms-legal-basis",
        "type" : "flat"
      },
      "severity" : "ERROR"
    }

the codelist-Folder contains no codelist with that name - only legal-basis and legal-basis_eforms-legal-basis.

In accordance to other codelist-defintions in fields.json, should the codelist-definition for BT-01-notice be changed into
"codeList" : {
      "value" : {
        "id" : "eforms-legal-basis",
        "type" : "flat"
        "parentId" : "legal-basis"
      },
      "severity" : "ERROR"
    }
?

**Comment by sbo2718** [comment]
The codelist property in the fields.json doesn't support a parentId.
It is defined in the coselists.json where a mapping is defined for the 'eforms-legal-basis', so this is a valid entry.

**Comment by bertrand-lorentz** [comment]
The filenames in the `codelists/` folder do not always correspond to the identifier of the codelist. See: https://docs.ted.europa.eu/eforms/latest/codelists/index.html#_filenames_of_tailored_codelist

You should use the content of the `codelists/codelists.json` to determine the filename corresponding to a codelist from an identifier.

Please see the section on the "codelist" property in the following page for explanations on the use of "parentId".
https://docs.ted.europa.eu/eforms/latest/fields/index.html#_dynamic_properties

The content of `fields.json` is correct for this aspect, so I'm closing this, as it's not an issue in the SDK.
