### ISSUE TITLE
eforms-sdk-1.7.0 missing some xsdSequenceOrder

### ISSUE THREAD

**Issue by luis-matos-healy-hudson** [OP-TED/eForms-SDK#490]
Hi, on eforms-sdk-1.7.0 xsdSequenceOrder was included that references the order.

i'm using this element to do the order, but i notice some elementes don't have order defined.

<efac:Changes />
<efac:Organizations />
<efac:Organization />
<efbc:NaturalPersonIndicator/>
<efbc:GroupLeadIndicator />
<efbc:AcquiringCPBIndicator />
<efac:NoticeSubType />
<efac:Publication />

On the Schema there is an order this also should be added no ?

<xsd:element name="EformsExtension">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="efbc:AccessToolName" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efbc:FrameworkMaximumAmount" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efbc:ProcedureRelaunchIndicator" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efbc:TransmissionDate" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efbc:TransmissionTime" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:AnswerReceptionPeriod" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:AppealRequestsStatistics" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:AppealsInformation" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:AwardCriterionParameter" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:BuyingPartyReference" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:Changes" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:ContractModification" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:FieldsPrivacy" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:Funding" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:InterestExpressionReceptionPeriod" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:NoticeResult" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:NoticeSubType" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:Organizations" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:Publication" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:SelectionCriteria" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:StrategicProcurement" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:SubsidiaryClassification" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:ReferencedDocumentPart" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:TenderSubcontractingRequirements" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
</xsd:schema>

<xsd:choice minOccurs="0" maxOccurs="1">
	<xsd:sequence>
		<xsd:element ref="efbc:GroupLeadIndicator" minOccurs="0" maxOccurs="1"/>
		<xsd:element ref="efbc:AcquiringCPBIndicator" minOccurs="0" maxOccurs="1"/>
		<xsd:element ref="efbc:AwardingCPBIndicator" minOccurs="0" maxOccurs="1"/>
	</xsd:sequence>
</xsd:choice>

**Comment by luis-matos-healy-hudson** [comment]
Thanks for the quick answer.

**Comment by bertrand-lorentz** [comment]
This will be corrected in SDK version 1.8.0.
