### ISSUE TITLE
Inter-dependent fields not both in the same notice type

### ISSUE THREAD

**Issue by klmdb** [OP-TED/eForms-SDK#498]
# Problem

File `notice-types/16.json` doesn't contain `OPT-060-Lot` BUT DOES contain `BT-70-Lot`.

# Analysis

`BT-70-Lot` depends on `OPT-060-Lot` to create the correct xml node:
  - `BT-70-Lot` xpath expression: `"/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:ContractExecutionRequirement[cbc:ExecutionRequirementCode/@listName='conditions']/cbc:Description"`
  - Assumes `[cbc:ExecutionRequirementCode/@listName='conditions']` to be present, in order to be able to parse it's value from the xml document.

Because we build the xml document based on the xpath expressions of the nodes in the conceptual model, we need `OPT-060-Lot` to be present in the conceptual model in order to create the xml node `<cbc:ExecutionRequirementCode listName="conditions">`.
It is not present in the conceptual model though, because it is not part of the `notice-type/16.json`.
  
# Solution

Include `OPT-060-Lot` into `notice-type/16.json`.
Check if this is a class of problems that needs to be solved generally.

**Comment by rouschr** [comment]
According to Enrico this will be fixed in SDK 1.8
