### ISSUE TITLE
efac:TenderLot(BT-13713-LotResult) tag with in efac:LotResult must be occur at least once for notice sub type 29 and 33.

### ISSUE THREAD

**Issue by pankajgulia111** [OP-TED/eForms-SDK#506]
Hello,
While generating form for notice subtype 29 and 33 i came  across this field **BT-13713-LotResult** , its meta data within fields.json file **does not have any mandatory constraints**.
So i created the XML without providing any value to this field , XML element **efac:NoticeResult** i generated is as below
``<efac:NoticeResult>
                  <efac:LotResult>
                     <cbc:ID>RES-0001</cbc:ID>
                     <cbc:TenderResultCode listName="winner-selection-status">selec-w</cbc:TenderResultCode>
                  </efac:LotResult>
                  <efac:LotTender>
                     <cbc:ID>TEN-0001</cbc:ID>
                  </efac:LotTender>
                  <efac:SettledContract>
                     <cbc:ID>CON-0001</cbc:ID>
                  </efac:SettledContract>
               </efac:NoticeResult>``
.On validation API call response the error message i get says that 
"Message={\"errorCode\":400,\"message\":\"The notice is an invalid XML against its XSD. See below the full error:\\n[{\\\"line\\\":17,\\\"column\\\":36,\\\"message\\\":\\\"cvc-complex-type.2.4.b: The content of element 'efac:LotResult' is not complete. One of '{\\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-basic-components/1\\\\\\\":DPSTerminationIndicator, \\\\\\\"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2\\\\\\\":FinancingParty, \\\\\\\"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2\\\\\\\":PayerParty, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":AppealRequestsStatistics, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":DecisionReason, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":LotTender, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":FrameworkAgreementValues, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":ReceivedSubmissionsStatistics, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":SettledContract, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":StrategicProcurement, \\\\\\\"http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1\\\\\\\":TenderLot}' is expected.\\\"}]\",\"timestamp\":\"2023-06-06T11:52:02Z\"}, statusCode=400"

. So i decided to check the schema inside http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1 namespace , from there these useful information i noticed
inside schema tag/
	<xsd:element name="LotResult" type="LotResultType"/>
and 
		``<xsd:complexType name="LotResultType">
		<xsd:sequence>
			<xsd:element ref="efac:FieldsPrivacy" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="cbc:ID" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="cbc:HigherTenderAmount" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="cbc:LowerTenderAmount" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="cbc:TenderResultCode" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efbc:DPSTerminationIndicator" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="cac:FinancingParty" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="cac:PayerParty" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:AppealRequestsStatistics" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:DecisionReason" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:LotTender" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:FrameworkAgreementValues" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="efac:ReceivedSubmissionsStatistics" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:SettledContract" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:StrategicProcurement" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="efac:TenderLot" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>``

as you can see above ``<xsd:element ref="efac:TenderLot" minOccurs="1" maxOccurs="1"/>``
tells that efac:TenderLot must occur at least once , and inside fields.json there is only field inside the** /efac:NoticeResult/efac:LotResult/efac:TenderLot** path. 
So i take it there should be a mandatory constraint telling this to mandatory with in 29 and 33 or where everever **efac:NoticeResult** is to be generated?
Regards, 
Pankaj

**Comment by bertrand-lorentz** [comment]
This issue was resolved in SDK 1.8.0, so I'm closing it.
