### ISSUE TITLE
Add Norwegian (NOR) to official langauge codelist?

### ISSUE THREAD

**Issue by kjorlaug** [OP-TED/eForms-SDK#534]
Norwegian (NOR) exists in the EU vocabulary list (https://publications.europa.eu/resource/authority/language) but is missing in the codelist in the SDK. The regulation itself (BT-702) only states that the main languages are the ones that are legally equally binding. Excluding EEA-languages is a deviation from the norm today and has big consequences for implementation in the Norwegian market...

Will you let us in? :)

--

Rune
DFØ - responsible for eForms in Norway

**Comment by ferrakaop** [comment]
eForms doesn't change the way Norweigian notices have been handled until now and we will continue to welcome notices from EEA and partner countries from outside the EU.

Please see more details in the discussion in https://github.com/OP-TED/eForms-SDK/pull/502

**Comment by kjorlaug** [comment]
Thanks for quick feedback. Erlend made me aware of his pull-request after I posted this - sorry for the double up.
