### ISSUE TITLE
Missing translation "rule|text|BR-BT-00262-0300"

### ISSUE THREAD

**Issue by klakegg** [OP-TED/eForms-SDK#538]
There are currently no translation of "rule|text|BR-BT-00262-0300" available in English as of 1.7 and as far as I can see for the upcoming 1.8.

**Comment by ferrakaop** [comment]
BR-BT-00262-0300 is the only rule of type "changeable", which aren't used in 1.8 (or 1.9), so we haven't added a label or translation for this rule yet.

**Comment by klakegg** [comment]
I don't understand why the rule referencing a translation wound not have a translation, could you please explain this?

Also, is definetly seem to be part of 1.8:
https://github.com/OP-TED/eForms-SDK/blob/1.8.0/schematrons/dynamic/validation-stage-6a.sch#L5

**Comment by bertrand-lorentz** [comment]
The rule BR-BT-00262-0300 is one the of the few rules that are supposed to use information from another notice.
This type of rule was never applied, as the service to fetch another notice is not available yet. So they were always silently failing, and never appearing in any validation report. And we indeed never translated the corresponding message.

As they were causing some problems and confusion, those ineffective rules will be removed in SDK 1.12.0.

So I'm closing this issue.
