### ISSUE TITLE
1.8.0 BT-702(b)-notice: parent missing from visual model

### ISSUE THREAD

**Issue by DeMol-EE** [OP-TED/eForms-SDK#549]
We were playing with the 1.8.0 RC and have started experiencing issues due to changes to BT-702(b)-notice, more specifically that this has changed from a repeatable field with relative XPath of 2 steps to a non-repeatable field in a repeatable parent (result of splitting the relative XPath). This in itself is fine, but the repeatable parent node is missing from the visual model, which is a violation of the rules concerning repeatable ancestors.

Perhaps this change should be reverted before 1.8.0 is released, since I’m not sure where to put the ancestor in the visual model as BT-702(b)-notice is considered metadata.

On that note, why do we distinguish between metadata in the visual model but not in the conceptual model? Could it be considered to mark a field as metadata in fields.json instead of having a dedicated metadata section in each notice type json file (perhaps for 2.0.0)? I’m not asking purely in the light of the issue described above, we have other cases in which it would be helpful to know what is metadata and what is not on the conceptual level.

**Comment by bertrand-lorentz** [comment]
This was resolved in SDK 1.8.0, so I'm closing this.
