### ISSUE TITLE
Tenders Search API - Query parameter value

### ISSUE THREAD

**Issue by udaykeith** [OP-TED/eForms-SDK#552]
### Discussed in https://github.com/OP-TED/eForms-SDK/discussions/551

<div type='discussions-op-text'>

<sup>Originally posted by **udaykeith** June 28, 2023</sup>
Hi, I am trying to search for tenders which fulfill certain criteria via /api/v3.0/notices/search. However, I am not sure how to structure the value for the "query" argument. It seems that no matter what I pass as the value for "query" I receive the same response. 

This is currently the code I am using:

```
import requests
import json

url = 'https://ted.europa.eu/api/v3.0/notices/search'  
api_key = TED_API_KEY 
query_ = 'notice-type=[cn-standard or pin-cfc-social]'

headers = {
    'Authorization': f'Bearer {TED_API_KEY}',
    'fields': "['ND', 'PD', 'CONTENT']",
    "query": "blah blah"
}


response = requests.get(url, headers=headers)
```

I receive a valid JSON with a 1000 results with this query. I have a query setup in Expert search and I used the same search query in my code but got the same results.</div>

**Comment by bertrand-lorentz** [comment]
This is not an issue related to the eForms SDK, but to the TED website, so I'm closing this.

**Comment by jtomek** [comment]
I'm sorry, but TED has the worst and least understandable API I have ever experienced.

Having said that, this works:

```bash
curl --location 'https://ted.europa.eu/api/v3.0/notices/search' \
--header 'Content-Type: application/json' \
--data '{
    "apiKey": "your-key",
    "fields": ["CONTENT"],
    "q": "PC=[320*]",
    "pageSize": "2"
}'
```
