### ISSUE TITLE
multiple Tenders submitted by the same Tendering Party

### ISSUE THREAD

**Issue by pietropalermoIT** [OP-TED/eForms-SDK#567]
I don't understand the business scenario in which multiple Tenders could be submitted by the same Tendering Party for the same lot/group of lot

**Comment by YvesJo** [comment]
Hi,
This kind of scenario may not be allowed in all countries and it could be the case in your own.
Consider a country where this would be possible and additionally the following Business Term defined in the Regulation Annex:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jourdyv/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jourdyv/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



++ | BT-769 | Multiple Tenders | No | Indicator | Tenderers may   submit more than one tender (for a given lot).
-- | -- | -- | -- | -- | --




</body>

</html>

I close the issue.
KR
