### ISSUE TITLE
OPT-300

### ISSUE THREAD

**Issue by pietropalermoIT** [OP-TED/eForms-SDK#575]
The OPT-300 appears in the examples but not in the documentation: why?

**Comment by rouschr** [comment]
For questions please use the github Discussions, unless you are certain it is a serious issue or bug.
If we determine that this is an issue we will create at ticket on our side to address it.

**Comment by YvesJo** [comment]
Hi,
OPT-300 is related to fields that don't exist in the regulation but are required by design. This information will be added to the "Parties" section of the documentation.

**Comment by pietropalermoIT** [comment]
OK, I did not understand at the begin the for this kind of evidences I was expected not to open an issue but to start a conversation

**Comment by YvesJo** [comment]
Documentation version 1.3, and later, will get fixed with the next publication.
