### ISSUE TITLE
BT-01

### ISSUE THREAD

**Issue by pietropalermoIT** [OP-TED/eForms-SDK#576]
Why the BT-01 representation appears twice in the documentation? first in Notice information (cbc:RegulatoryDomain) and also in Legal basins (BT-01)? from a semantic point of view the same information is represented in two distinct cbc?

**Comment by YvesJo** [comment]
Hi,
The element cbc:RegulatoryDomain (field BT-01-notice) is used to report the legal basis that drives the notices publications (e.g. Directive 24).
Amongst the requirements, requests were made to have the opportunity to specify further (local) legal basis relevant for the procedure and this could be performed by defining these additional optional fields.
I close this conversation as it is not a technical issue.
Thanks for your understanding.
KR
