### ISSUE TITLE
cbc:DocumentStatusCode

### ISSUE THREAD

**Issue by pietropalermoIT** [OP-TED/eForms-SDK#581]
cbc:DocumentStatusCode is linked to
-  the list-name document-status in the example CN24 maximal 
- the list-name linguistic-status in the specification Procurement documents (BT-14, BT-15, BT-615, BT-707, BT-708, BT-737)
Which is the correct indication?

**Comment by YvesJo** [comment]
Hi,
The expected listName attribute should be "linguistic-status" instead.
Please also note that this field (OPT-050) will disappear with SDK 1.9
KR
