### ISSUE TITLE
buyer-contracting-type'

### ISSUE THREAD

**Issue by pietropalermoIT** [OP-TED/eForms-SDK#584]
Code list missing in https://op.europa.eu/en/web/eu-vocabularies/authority-tables

**Comment by ferrakaop** [comment]
buyer-contracting-type is one of the "technical" codelists, which are not in EU Vocabularies.  There are other codelists that are only available in the SDK: https://docs.ted.europa.eu/eforms/latest/reference/code-lists/index.html#_technical_codelists

**Comment by pietropalermoIT** [comment]
Thank

**Comment by rouschr** [comment]
You can see all the codelists here:
https://github.com/OP-TED/eForms-SDK/tree/develop/codelists
If you select (develop) on the top left, you can select tags and see this for every SDK version.

**Comment by pietropalermoIT** [comment]
I thanked yesterday, sorry i did not close the issue
