### ISSUE TITLE
attributes, attributeOf and attributeName are not defined

### ISSUE THREAD

**Issue by jpmckinney** [OP-TED/eForms-SDK#601]
Other field properties are defined at https://docs.ted.europa.eu/eforms/latest/fields/index.html

**Comment by jpmckinney** [comment]
Aha so does main branch = /latest/ docs?

**Comment by bertrand-lorentz** [comment]
Yes, the "main" branch of the eForms-SDK repository should normally correspond to the docs available under /latest/.
