### ISSUE TITLE
eNotices2 application in preview environment not able to display notices submitted using SDK 1.6

### ISSUE THREAD

**Issue by alexmohora** [OP-TED/eForms-SDK#629]
Hello,

We've done many tests using the preview environment and are using the app. eNotices2 in order to view the XML content submitted, either as PDF or HTML.

We are using SDK 1.6.

None of these files are fully displayed. If we send it marked as SDK 1.7 compliant then the display is ok (no other modification in the file).

I believe that the eNotices2 app is trying to convert the XML to the sdk 1.7 or 1.8 and this conversion fails. Then is calling the view service using the converted file to get the PDF/HTML

It would be a massive help to us and our users if the eNotices2 app would correctly display all information for SDK 1.6.

Many thanks,
Alex Mohora
 
Please see some print screens:
![Screenshot_96](https://github.com/OP-TED/eForms-SDK/assets/115160065/bc6bf99d-acc6-4f08-9e27-abe64345475d)
![Screenshot_95](https://github.com/OP-TED/eForms-SDK/assets/115160065/e0d1dc5f-549f-4c27-9f58-eafcf3ba93ea)
![Screenshot_94](https://github.com/OP-TED/eForms-SDK/assets/115160065/19be63d1-5877-4327-a8a7-54856773438c)
![Screenshot_93](https://github.com/OP-TED/eForms-SDK/assets/115160065/a7be5a45-5b14-4031-bb05-25772f047cfb)

**Comment by rouschr** [comment]
Hello,

thank you for the feedback but this is enotices2 related and you have to go through their helpdesk:
https://enotices2.ted.europa.eu/help/contact
As your github issue is public you can provide them the link to it if you want to avoid redoing the work.

**Comment by bertrand-lorentz** [comment]
As this is not an issue with the eForms SDK, I'm closing it.
