### ISSUE TITLE
Wrong Translation in notice_de.xml

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#667]
<entry key="notice|name|20">Auftragsbekanntmachung – allgemeine Richtlinie, Sonderregelung</entry>
<entry key="notice|name|21">Auftragsbekanntmachung – allgemeine Richtlinie, Sonderregelung</entry>

The german translation for notice 21 is wrong. 

The translation should be: "Auftragsbekanntmachung –Sektorenrichtlinie, Sonderregelung".

**Comment by ferrakaop** [comment]
Thanks for spotting this - we will look into it asap.  It looks like the 2019 eForms regulation has this mistake.

**Comment by ferrakaop** [comment]
The German translation will be corrected in the next amendment to the eForms regulation.

In the meantime we will also correct it in the next SDK release (and the label will be included in the patches to the previous SDK versions).

Thanks again for spotting this.

**Comment by bertrand-lorentz** [comment]
The corrected labels will be included in SDK 1.9.0.
See commit 292f3f2b.
So I'm closing this issue.
