### ISSUE TITLE
PDF DOWNLOAD

### ISSUE THREAD

**Issue by ferdinandjmaddela** [OP-TED/eForms-SDK#683]
In eNotice2 the PDF that we download is a PDF/A compatible?

**Comment by bertrand-lorentz** [comment]
Please only create an issue in this repository for potential problems or bugs in the content of the eForms SDK.

For questions about eNotices2, please use the contact form in the application itself:
https://enotices2.ted.europa.eu/help/contact

So I'm closing this issue.
