### ISSUE TITLE
Handling Visual model to generate Conceptual Model  - why is lot group missing ?

### ISSUE THREAD

**Issue by labruno** [OP-TED/eForms-SDK#700]
Playing with notice16, and sdk 1.8.0, I've noticed in the eforms-notice-editor , that after using the utility "generate XML" the field id "BT-137-Lot" is not included in the ConceptualModel and eventually not part of XML physical model.
Some story happens for most of the nodes under group/node "GR-Lot-Purpose _ ND-LotTenderingProcess".

IMHO I do believe this is NOT  the expected behavior.

Checking out the demo, somehow the logic discharges the field "BT-137-Lot" saying that there's a problem in the VIsualModel since the expected parent node, as per fields.json, is different.
The fields.json says the parent node for "BT-137-Lot"  is the "ND-Lot". The visual model, as per notice type 16.json, says the parent is "ND-LotTenderingProcess" ( where "ND-Lot" is actually the ancestor of "BT-137-Lot" being the parent of ND-LotTenderingProcess".

IMHO the Visual Model is perfectly fine respecting the 16.json as well as the Concept Model is legitimate to put under another node the fields as per  fields.json.

I don't get the logic written at the method "handleVisualField" of "VisualModel" class, which is a bit confusing to me.
Could you so kind to support me to better understand the case scenario of field "BT-137-Lot" for notice type 16 and what's the logic to apply to have all the proper fields also in the XML?
Is it possible to get in touch in some Chat rooms for developers?
is it the code ok and ther' something wrong with the json files or vice-versa ?

Thank you in advance. 😃 

_Adding a snippet of your code:_
```java

.....
if (!closestParentNode.getNodeId().equals(sdkParentNodeId)) {
      // The parents do not match.   <--------------   Why is this a problem ?
      final boolean isRepeatable = fieldsAndNodes.isNodeRepeatable(sdkParentNodeId);
      if (isRepeatable) {
        // The SDK says the desired parentNodeId is repeatable and is missing in the visual model,
        // thus we have a serious problem!   <----------------------- Why   ?
        final String msg = String.format(
            "Problem in visual node hierarchy, fieldId=%s is not included"
                + " in the correct parent. Expecting %s but found %s as closestParentNode id",
            sdkFieldId, sdkParentNodeId, closestParentNode.getNodeId());
        System.err.println(msg);
        // throw new RuntimeException(msg);
      }
.......
```

**Comment by labruno** [comment]
Thanks for the answer.
My question is a bit more straight if I may.
 Can you pls confirm the notice type 16.json and fields.json are 100% correct in SDK 1.8.0 and it's right the parent node for "BT-137-Lot" is the "ND-Lot" for a well formed concept model the SDK is looking for?

**Comment by rouschr** [comment]
The fields.json of the SDK is the reference for the XML generation:

    "id" : "BT-137-Lot",
    "parentNodeId" : "ND-Lot",
    
If the notice type contradicts this in terms of ancestry then there is a problem somewhere in the notice type.
Some of these notice type problems may also depend on how the algorithm going from visual, conceptual and physical works (how tolerant the algorithm etc.).

**Comment by labruno** [comment]
Is there any possible open-source code we could check in order to have a concrete ready-to-production example where understand the correct application of SDK principle? Would it be possible to inspect for instance enotices2 portal source code at https://enotices2.ted.europa.eu/home  ?

**Comment by rouschr** [comment]
Using SDK 1.9 and this branch of the editor demo: https://github.com/OP-TED/eforms-notice-editor/tree/feature/TEDEFO-2456-use-of-fields-attribute-information
With an empty form having 2 lots (LOT-0001 and LOT-0002) using notice sub type 16.
I obtain this XML:
[16-physical.xml.txt](https://github.com/OP-TED/eForms-SDK/files/12871958/16-physical.xml.txt)
Now that SDK 1.9 was released, let me know what kind of XML you can generate using notice 16.

**Comment by rouschr** [comment]
I worked on an old idea on how to improve the unit tests using xpath and found a problem which was not covered previously.
I fixed the problem in the branch and the new improved unit tests are passing now.
It is recommended you do a `git pull` to get the latest version of the branch and try again.
