### ISSUE TITLE
rule  `BR-BT-00743-0100` contradicts current German legislation and practice

### ISSUE THREAD

**Issue by rkottmann** [OP-TED/eForms-SDK#754]
Hi,

the rule 
`BR-BT-00743-0100` contradicts current German legislation and practice. Although the whole public administration is required- and able to receive eInvoices in the national tailoring of EN16931 implementing 2014/55/EU named "XRechnung" (https://xeinkauf.de/xrechnung/) we can NOT force EVERY private entity in ALL cases. 

Hence we need to be able to additionaly also choose `allowed` in addition to `required` .

**Comment by YvesJo** [comment]
Hi,
This rule is deactivate since SDK 1.9

**Comment by rkottmann** [comment]
Thx, this is good news. However would it possible to also deactivate it for 1.7.x and 1.5.x? Because these are the versions currently in active use in Germany.
