### ISSUE TITLE
Wrong Translation in field_de.xml

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#760]
The german translation von "field|description|BT-134-Lot" and "field|description|BT-134-Lot-Language" is wrong. 

The second word between the brackets should be "Angaben" not "Anhaben".

**Comment by YvesJo** [comment]
Hi, 
Are you referring to BT-134 "Weitere Informationen über die öffentliche Öffnung der Angebote (beispielsweise An**h**aben dazu, wer an der Öffnung teilnehmen kann und ob eine Genehmigung erforderlich ist)." ?

**Comment by GarrusMD** [comment]
Yes. BT-134-Lot-Language and BT-134-Lot

**Comment by YvesJo** [comment]
Fixed with SDK 1.10
