### ISSUE TITLE
Missing fields : BT-770, BT-715, BT-725 ,BT-716 (from (EU) 2019/1780)

### ISSUE THREAD

**Issue by Tronquill** [OP-TED/eForms-SDK#773]
Hi, As part of the national customization (tailoring), we need to mark the BT-770 (Organization Subrole), BT-715 (Vehicles), BT-725 (Vehicles Zero Emission) and BT-716 (Vehicles Clean) fields as required (https://docs.ted.europa.eu/eforms/latest/reference/business-terms/index.html). I could not find these fields in the definition of all fields in the SDK.  Do you plan to add them to the SDK in the near future, and if not, did you plan a way to expand the definition of fields and notification type fields in the SDK for developers (we don't want to break cooperation during version updates)?

**Comment by YvesJo** [comment]
Hi,
This is not an issue and information will be provided in [the discussion](https://github.com/OP-TED/eForms-SDK/discussions/774)
KR
