### ISSUE TITLE
Contradictive rules regarding procedure types in VEAT forms 25, 26, 27, 28

### ISSUE THREAD

**Issue by Colan71** [OP-TED/eForms-SDK#790]
Dear Team,

In the specifications for SDK 1.10, we can see in the code lists for VEAT forms 25--28 (for example: procurement-procedure-type_procedure-type-25.gc) that the type of procedures allowed are:
Negotiated without prior call for competition
Other multiple stage procedure
Other single stage procedure

However, there is a validation rule stopping the Procurement officers to choose any other type of procedure type then "Negotiated without prior call for competition":
rule|text|BR-BT-00105-0109">If 'Notice type' (BT-02) is 'Voluntary ex-ante transparency notice', then 'Type of procedure' (BT-105) must be 'Negotiated without prior call for competition'. 

Will the rule rule|text|BR-BT-00105-0109 be changed and procedure types "Other multiple stage procedure" and "Other single stage procedure" will be accepted for VEAT forms, or how will this be addressed and when?

Best regards,
Åsa

**Comment by YvesJo** [comment]
Hi,
The rule associated to the label in question is not part of SDK 1.10 so users shouldn't be stopped from using the "Other ... stage procedure" .
Please let us know if you however still face the issue.
KR

**Comment by YvesJo** [comment]
No such active rule that would contradict what is actually allowed for DAP.
