### ISSUE TITLE
Schematron rule "BR-OPT-00002-005 broken since 1.10

### ISSUE THREAD

**Issue by DeMol-EE** [OP-TED/eForms-SDK#807]
Since 1.10, evaluating the schematrons is giving a new error. The failing test:

    matches(normalize-space(.),'^eforms-sdk-\\d\\.\\d$'

This can be reproduced by applying the schematrons on the provided examples. Perhaps the regex should be adapted to `\\d+`?

**Comment by bertrand-lorentz** [comment]
Hello,
This regex pattern has already been corrected for version 1.10.0. See commit f815cf4bf.
Maybe you're looking at Schematron files from an older SDK version ?

**Comment by DeMol-EE** [comment]
Wait, this was fixed in september 2023?! Thanks @bertrand-lorentz, I’ll have a look at our internal process.
