### ISSUE TITLE
Direct Award in subtyp "T01"

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#830]
Subtype T-01 contains the group "GR-Procedure-DirectAward". However, it is currently not possible to fill the only field in this group (BT-136-Procedure), as this field can only be filled if the procedure type (BT-105) is "neg-wo-call". However, the only valid procedure type for subtype T-01 is "comp-tend".

**Comment by YvesJo** [comment]
Thanks for reporting.
Some clarification were going on and this will get fixed with SDK 1.11.
