### ISSUE TITLE
BR-BT-01118-0100 OverallApproximateFrameworkContractsAmount decimal value issues

### ISSUE THREAD

**Issue by DeanFirkelj** [OP-TED/eForms-SDK#845]
Hi,
There seems to be a problem with the validation BR-BT-01118-0100 in case when ReestimatedValueAmount for Framework agreement values for multiple lots are decimal values and the OverallApproximateFrameworkContractsAmount also expressed as a decimal value.
Example
Lot 1:
 <efac:FrameworkAgreementValues>
      <efbc:ReestimatedValueAmount currencyID="EUR">6685227.60</efbc:ReestimatedValueAmount>
</efac:FrameworkAgreementValues>
Lot 2:
<efac:FrameworkAgreementValues>
      <efbc:ReestimatedValueAmount currencyID="EUR">1406463.60</efbc:ReestimatedValueAmount>
</efac:FrameworkAgreementValues>

Lot 3:
<efac:FrameworkAgreementValues>
      <efbc:ReestimatedValueAmount currencyID="EUR">5072417.60</efbc:ReestimatedValueAmount>
</efac:FrameworkAgreementValues>

Lot 4:
<efac:FrameworkAgreementValues>
      <efbc:ReestimatedValueAmount currencyID="EUR">4304438.96</efbc:ReestimatedValueAmount>
</efac:FrameworkAgreementValues>

<efbc:OverallApproximateFrameworkContractsAmount currencyID="EUR">17468547.76</efbc:OverallApproximateFrameworkContractsAmount>

Version 1.10 SDK.

Regards

**Comment by YvesJo** [comment]
Hi,
There is a calculation concern with decimals and calculation, this will get fixed with SDK 1.11. For previous SDK version, the workaround is to use integers instead.
