### ISSUE TITLE
A buyer can not be a service provider

### ISSUE THREAD

**Issue by DeanFirkelj** [OP-TED/eForms-SDK#856]
Hi,

SDK v1.10

We have an issue with this case when eSender also acts as a contracting authority. If we create just one organization node, this validation rule prevents such situation:

<svrl:failed-assert id="BR-OPT-00300-0254" location="/cn:ContractNotice" test="every $sps in cac:ContractingParty/cac:Party/cac:ServiceProviderParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text()) satisfies not($sps = cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text()))" role="ERROR" xmlns:svrl="http://purl.oclc.org/dsdl/svrl">
  <svrl:text>A buyer can not be a service provider</svrl:text>
  <svrl:diagnostic-reference diagnostic="ND-Root_OPT-300-Procedure-Buyer" see="field:OPT-300-Procedure-Buyer">
    <svrl:text>cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID</svrl:text>
  </svrl:diagnostic-reference>
</svrl:failed-assert>

In case when we create two organizations with same Company ID, then (OFC) another validation kicks in requiring to have unique company IDs. 

We created a workaround in this case, but please try to solve it in the future versions.

P.S. Additionally the same eSender will surely act as tenderer in some other future procurements (where they will also be eSenders), so please keep in mind also this scenario.

KR,
Dean

**Comment by YvesJo** [comment]
Hi,
Thanks for reporting this, we'll remove the constraint on the e-Sender

**Comment by mdewinne** [comment]
In Belgium we had the same problem. Our organisation is the national TED eSender, but at the same time it (or certain other divisions within our org) can act as a contracting authority.

We "solve" it by creating two organisations with two different company IDs. The CA org uses the regular VAT number from the national business registry as company ID, whereas the eSender org uses our TED account identifier ("eSender ID") as company ID.

**Comment by YvesJo** [comment]
HI,
Constraints BR-OPT-00300-0254 on Buyer and BR-OPT-00300-0257 on Tenderer will be removed with SDK 1.13.
KR
