### ISSUE TITLE
Notice viewer failing on SDK 1.10.1, notice subtype 16

### ISSUE THREAD

**Issue by gediminasre** [OP-TED/eForms-SDK#860]
Hi, when transforming sdk-1.10.1 notice.xml, getting some strange error:

>Error at char 61 in expression in xsl:value-of/@select on line 3738 column 287 
  FORG0001  The string "Grundlegende Informationen zur..." cannot be cast to a boolean
at template block0401150605 on line 3729 column 42 
     invoked by xsl:call-template at #3633
at template block04011506 on line 3612 column 40 
     invoked by xsl:call-template at #3103
at template block040115 on line 3081 column 38 
     invoked by xsl:call-template at #1465
at template block0401 on line 1410 column 36 
     invoked by xsl:call-template at #1406
at template block04 on line 1399 column 34 
     invoked by xsl:call-template at #152

For some reason strings from "business-term_de.xml" file are tried to cast to boolean. Some other notice-subtypes works fine, but subtype 16 is failing. Tried running same file with sdk version 1.7 and it works.
 See attached file, which is failing.
[cn_24_maximal[1].zip](https://github.com/OP-TED/eForms-SDK/files/14603276/cn_24_maximal.1.zip)

**Comment by pdonohoe** [comment]
Hi @gediminasre,
That is a very strange error. The only label that contains the text "Grundlegende Informationen zur" is for Business Group BG-1, which has the label in German "Grundlegende Informationen zur Bekanntmachung." The EFX used in the notice viewer does not use or display BG-1, and I can get the notice displayed correctly with no error.
You say "when transforming sdk-1.10.1 notice.xml" - what exactly are you trying to do? what application are you using?
Thanks,
Paul

**Comment by gediminasre** [comment]
@pdonohoe Thanks for answering. We are using notice viewer to display xml notices in html/pdf format. And it was working in previous 1.5, 1.7 versions. The newest 1.10.1 has this strange error. Does my attached file in the first message work for you with no issues?

**Comment by gediminasre** [comment]
@pdonohoe can you please guide me to the code/repository, which does the notice rendering and it works with the provided notice example? I would like to investigate your working code. Thanks!
