### ISSUE TITLE
1.8.2: Result section in the cancellation notice is missing in the rendered HTML/PDF

### ISSUE THREAD

**Issue by rgannu** [OP-TED/eForms-SDK#862]
In 1.8.2, in the cancellation notice (contract award notice with notice subtype 29), we could see the notice result as follows:
(Contract award notice without tenders e.g. to "cancel" one or more lots in an ongoing procedure, the rendered HTML/PDF notice does not contain a result section)

```
<efac:NoticeResult>
  <efac:LotResult>
	  <cbc:ID schemeName="result">RES-0001</cbc:ID>
	  <cbc:TenderResultCode listName="winner-selection-status">open-nw</cbc:TenderResultCode>
	  <efac:TenderLot>
		  <cbc:ID schemeName="Lot">LOT-0001</cbc:ID>
	  </efac:TenderLot>
  </efac:LotResult>
  <efac:LotResult>
	  <cbc:ID schemeName="result">RES-0002</cbc:ID>
	  <cbc:TenderResultCode listName="winner-selection-status">clos-nw</cbc:TenderResultCode>
	  <efac:DecisionReason>
		  <efbc:DecisionReasonCode listName="non-award-justification">chan-need</efbc:DecisionReasonCode>
	  </efac:DecisionReason>
	  <efac:TenderLot>
		  <cbc:ID schemeName="Lot">LOT-0002</cbc:ID>
	  </efac:TenderLot>
  </efac:LotResult>
  <efac:LotResult>
	  <cbc:ID schemeName="result">RES-0003</cbc:ID>
	  <cbc:TenderResultCode listName="winner-selection-status">clos-nw</cbc:TenderResultCode>
	  <efac:DecisionReason>
		  <efbc:DecisionReasonCode listName="non-award-justification">ins-fund</efbc:DecisionReasonCode>
	  </efac:DecisionReason>
	  <efac:TenderLot>
		  <cbc:ID schemeName="Lot">LOT-0003</cbc:ID>
	  </efac:TenderLot>
  </efac:LotResult>
</efac:NoticeResult>
 
```

_When the notice is rendered as HTML/PDF the **"Results" section is missing in 1.8.2** where as it is available in 1.8.0 version._

In 1.8.0, the EFX view template (29.efx) checks the following for displaying the “Results” section

```
6 {ND-Root[(BT-13713-LotResult is present)]} #{auxiliary|text|results} // 6. Results
```

`BT-13713-LotResult: `
```
"xpathAbsolute" : "/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotResult/efac:TenderLot/cbc:ID",
```
Here `TenderLot` is present and hence the section appears in the HTML/PDF.

where as in 1.8.2 (29.efx) , 
```
6 {ND-Root[(BT-3201-Tender is present)]} #{auxiliary|text|results} // 6. Results
```

`BT-3201-Tender`: 
```
"xpathAbsolute" : "/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotTender/efac:TenderReference/cbc:ID",
```
`LotTender` section doesn’t exist in the Notice XML and hence the rendered HTML/PDF doesn’t contain the section “Results”. 

If the generated XML is fine, then why the view template that has been changed from 1.8.0 to 1.8.2?

**Comment by pdonohoe** [comment]
Dear @rgannu, the change was made to the EFX template between 1.8.0 and 1.8.2 to fix a different case where the Results section was not displayed. Unfortunately, this change caused the problem you report, where the Results section is not displayed if there are no LotTenders. This will be fixed with the release of SDK 1.11, and the fix will then be applied to previous SDK versions.
