### ISSUE TITLE
Faulty Group-Definitions in several Notice-Types.

### ISSUE THREAD

**Issue by duranalp** [OP-TED/eForms-SDK#870]
We found different Group Definition `GR-Procedure-Description` in several Notice-Types.
In our point of view, these group definition shall be same in all notice types.

We assume that the correct Definition is in Notice-Type 16.json

```json
"id" : "GR-Procedure-Description",
        "contentType" : "group",
        "displayType" : "GROUP",
        "description" : "Description",
        "_label" : "group|name|GR-Procedure-Description",
```

In several Notice Types for e.g. Notice-Type 29.json the group is defined wrong

```json
        "id" : "GR-Procedure-Description",
        "contentType" : "group",
        "nodeId" : "ND-ProcedureProcurementScope",
        "displayType" : "GROUP",
        "description" : "Scope of the Procurement addressed with the whole notice",
        "_label" : "group|name|ND-ProcedureProcurementScope"
```

We are using SDK 1.10.x we asking also for a patch of the SDK 1.10.x

**Comment by duranalp** [comment]
Hi i want to slightly ask if you have an update for this issue?

**Comment by duranalp** [comment]
Now 3 Weeks are gone, and i did not get any feedback. Why?

**Comment by bertrand-lorentz** [comment]
Sorry for the delayed response.

The difference is that in 29.json (and other notice subtypes), this group is associated with the node "ND-ProcedureProcurementScope". In 16..json it is not the case.
This is indeed inconsistent. This association might not be correct, as there are fields under ND-ProcedureProcurementScope that are not shown under GR-Procedure-Description.

We will review this and correct it in a future SDK version.

**Comment by GarrusMD** [comment]
Is there an update for this issue?

**Comment by GarrusMD** [comment]
I have just seen that in the RC for 1.12 the label in subtype 16 has been changed:

 "id" : "GR-Procedure-Description",
        "contentType" : "group",
        "nodeId" : "ND-ProcedureProcurementScope",
        "displayType" : "GROUP",
        "description" : "Scope of the Procurement addressed with the whole notice",
        "_label" : "group|name|ND-ProcedureProcurementScope",

In my opinion, this change is incorrect. The label "group|name|GR-Procedure-Description" should be the correct one for the "GR-Procedure-Description.

I agree with @duranalp that the flaw is in subtype 29 (and other notice subtypes).

**Comment by GarrusMD** [comment]
@bertrand-lorentz @YvesJo

**Comment by YvesJo** [comment]
Hi,
Groups and associated labels are purely for the UI. As indicated in § 3.9 of the eForms Policy Implementation Handbook:

> Labels are the texts used in user interfaces for manually filled fields. They are based on simplified eForms descriptions (parts of the descriptions appear as tooltips). The Publications Office of the EU will offer default set of labels in all EU official languages, used in the eNotices2 software application and in the TED website.
> Designers could make eProcurement systems more user-friendly by tailoring labels further. For example, labels can be tailored based on users (e.g. professional procurers may prefer legal terminology, SMEs and occasional procurers may prefer more user-friendly terminology), the system (e.g. form-filling vs. form-displaying), etc.

The most appropriate option has been selected given the constraints and the need to have this fixed for SDK 1.12.
KR

**Comment by GarrusMD** [comment]
I understand that the labels are purely for the UI. But I am still of the opinion that nodeID and label were simply assigned incorrectly here. No information on tendering terms are recorded in this group.

**Comment by GarrusMD** [comment]
@bertrand-lorentz  @YvesJo  Can you please check my last comment. We are currently testing the SDK 1.12 and as I feared, the wrong name for the group "GR-Procedure-Description" is now displayed in all places.

**Comment by YvesJo** [comment]
Hi,
There are fields in the description that depend on node ND-ProcedureProcurementScope and the node needs to be kept. The label for the group will be changed back to "Description"
