### ISSUE TITLE
Missing translations in sdk.

### ISSUE THREAD

**Issue by Tronquill** [OP-TED/eForms-SDK#882]
Hi, it looks like there are no translations for the group|name|ND-DirectAward  in Polish.

**Comment by YvesJo** [comment]
Hi,
In which SDK version?

**Comment by Tronquill** [comment]
I searched in versions <1.10 and 1.11 (in release branch)

**Comment by YvesJo** [comment]
I can find it in 1.11 release candidates but can't find it in 1.10. I guess this will get updated in previous versions once 1.11 officially released.

**Comment by bertrand-lorentz** [comment]
This label will be indeed be included in SDK 1.11.0 (it is already present in the corresponding branch), and it will then be backported to older active versions in future patch versions: 1.10.x, etc.

**Comment by Tronquill** [comment]
great, thanks
