### ISSUE TITLE
Conflicting SDK fields.json rules in version 1.10.1

### ISSUE THREAD

**Issue by Havunen** [OP-TED/eForms-SDK#894]
Hi,

We are having trouble to create a contract modification notice (i.e. EF 38) which contains framework agreement.

We cannot give values for BT-118 (Notice Framework Maximum Value) and BT-1118 (Notice Framework Approximate Value) even though they have specific forbidden rules defined for EF 38

Take a look at BT-118 fields.json:
https://github.com/OP-TED/eForms-SDK/blob/1.10.1/fields/fields.json#L3238-L3243

BT-118 forbidden condition for ef38:
```json
...
  "noticeTypes" : [ "25", "26", "27", "38", "39" ],
  "condition" : "{ND-NoticeResult} ${(BT-13713-LotResult in BT-137-Lot[BT-765-Lot not in ('fa-mix','fa-w-rc','fa-wo-rc')]) or (BT-709-LotResult is not present)}",
  "value" : true,
  "severity" : "ERROR"
...
```

It asserts BT-118 is forbidden when BT-765 does not have a framework agreement defined.

The problem raises because BT-765 is always hard-coded forbidden for EF 38 so it cannot have any value

https://github.com/OP-TED/eForms-SDK/blob/1.10.1/fields/fields.json#L31542-L31550

Is this a bug in SDK or are we missing something here?

**Comment by Havunen** [comment]
> Hi,
This is a bug whose fix is already in SDK 1.11 and will get backported

Okay, do you have any ETA for 1.10.2 ?

**Comment by Havunen** [comment]
IMO, hot-fixing current latest stable production release should have a higher priority than working on upcoming new features. SDK 1.10.1 was released Dec 21 2023 and haven't been patched since. We are upgrading from 1.7 to 1.10 this weeks Thursday so it becomes production issue for Finland then.

**Comment by YvesJo** [comment]
Hi,
I understand your concern and we do our best to have the least issues in the hand of the SDK users. To achieve this, some time is required to do the necessary quality controls.
The current issue had only been detected recently and couldn't be addressed earlier. Backporting will take place once SDK 1.11 released.
