### ISSUE TITLE
Structure of GR-Part-PlannedDuration

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#898]
With SDK 1.8 the structure of the GR-Lot-PlannedDuration group has been simplified. Unfortunately, this simplification has not yet been adopted for the group GR-Part-PlannedDuration (notice types 4-6). 

For example the notice type defintions of subtyp 4 and 16:

notice-type definiton subtyp 16:
{
        "id" : "GR-Lot-PlannedDuration",
        "contentType" : "group",
        "displayType" : "GROUP",
        "description" : "Planned Duration",
        "_label" : "group|name|GR-Lot-PlannedDuration",
        "content" : [ {
          "id" : "BT-538-Lot",
          "contentType" : "field",
          "displayType" : "COMBOBOX",
          "description" : "Duration Other",
          "_label" : "field|name|BT-538-Lot"
        }, {
          "id" : "BT-536-Lot",
          "contentType" : "field",
          "displayType" : "TEXTBOX",
          "description" : "Duration Start Date",
          "_label" : "field|name|BT-536-Lot"
        }, {
          "id" : "BT-537-Lot",
          "contentType" : "field",
          "displayType" : "TEXTBOX",
          "description" : "Duration End Date",
          "_label" : "field|name|BT-537-Lot"
        }, {
          "id" : "BT-36-Lot",
          "contentType" : "field",
          "displayType" : "TEXTBOX",
          "description" : "Duration Period",
          "_label" : "field|name|BT-36-Lot"
        } ]
      }

notice-type definiton subtyp 4:
{
        "id" : "GR-Part-PlannedDuration",
        "contentType" : "group",
        "displayType" : "GROUP",
        "description" : "Planned Duration",
        "_label" : "group|name|GR-Part-PlannedDuration",
        "content" : [ {
          "id" : "GR-Part-PlannedDuration-Dates",
          "contentType" : "group",
          "displayType" : "GROUP",
          "description" : "Duration Dates",
          "_label" : "group|name|GR-Part-PlannedDuration-Dates",
          "content" : [ {
            "id" : "BT-536-Part",
            "contentType" : "field",
            "displayType" : "TEXTBOX",
            "description" : "Duration Start Date",
            "_label" : "field|name|BT-536-Part"
          }, {
            "id" : "BT-537-Part",
            "contentType" : "field",
            "displayType" : "TEXTBOX",
            "description" : "Duration End Date",
            "_label" : "field|name|BT-537-Part"
          } ]
        }, {
          "id" : "GR-Part-PlannedDuration-Period",
          "contentType" : "group",
          "displayType" : "GROUP",
          "description" : "Duration Period",
          "_label" : "group|name|GR-Part-PlannedDuration-Period",
          "content" : [ {
            "id" : "BT-36-Part",
            "contentType" : "field",
            "displayType" : "TEXTBOX",
            "description" : "Duration Period",
            "_label" : "field|name|BT-36-Part"
          } ]
        }, {
          "id" : "BT-538-Part",
          "contentType" : "field",
          "displayType" : "COMBOBOX",
          "description" : "Duration Other",
          "_label" : "field|name|BT-538-Part"
        } ]
      }

**Comment by YvesJo** [comment]
Hi,
Thanks for reporting this issue, this will get fixed in SDK 1.12
KR

**Comment by GarrusMD** [comment]
Thanks!

**Comment by YvesJo** [comment]
This has been fixed and won't however get backported
