### ISSUE TITLE
Sum of criterias validation error

### ISSUE THREAD

**Issue by sne-vvz** [OP-TED/eForms-SDK#906]
Hello,

we are experiencing a problem with form validation. Customer has a form with more than 50 criteria and most of them are decimal numbers. There is a validation rule which says the sum of these criteria must be exactly 100. Although the sum of data is 100, the schematron validation fires the error. Please could you check why this form is firing the error? Please find the form as an attachment.

Thank you in advance for helping us with this issue.

> <svrl:failed-assert location="/Q{urn:oasis:names:specification:ubl:schema:xsd:ContractNotice-2}ContractNotice[1]/Q{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}ProcurementProjectLot[1]/Q{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}TenderingTerms[1]/Q{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}AwardingTerms[1]/Q{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}AwardingCriterion[1]" role="ERROR" id="BR-BT-00539-0200" test="sum(cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterNumeric[../efbc:ParameterCode/normalize-space(text()) = 'per-exa']/number()) = 100 or not(cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterNumeric[../efbc:ParameterCode/normalize-space(text()) = 'per-exa'])"><svrl:diagnostic-reference diagnostic="BT-543-Lot"><svrl:text id="BT-543-Lot" see="field:BT-543-Lot">cbc:CalculationExpression</svrl:text></svrl:diagnostic-reference><svrl:text>rule|text|BR-BT-00539-0200</svrl:text></svrl:failed-assert>

xml file of the said form:
https://gist.github.com/sne-vvz/3b3ba83172ea71be62dd2dbc24eec7eb

**Comment by YvesJo** [comment]
Hi,
This a calculation precision issue. An similar issue has already been reported for another calculation and both will get fixed with SDK 1.11.
The XML instance is an SDK 1.8 one, given the number of criteria, the use of whole numbers won't be possible without loosing information. Using "poi-exa" instead of "per-exa" could help as the rules wouldn't then get applied.
