### ISSUE TITLE
Missing translations in subtype T02

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#907]
Unfortunately, some (german) translations are missing in subtype T02. There are no translations for the following groups and fields:

- GR-Assets-Extended-Duration
- GR-SettledContract-3
- GR-LotTender-RevenueAllocation
- OPP-035-Tender

**Comment by YvesJo** [comment]
Hi,
Thanks for reporting this will get fixed as soon as labels corrections will get backported

**Comment by GarrusMD** [comment]
@YvesJo As far as I can see, the errors have now been fixed. The ticket can therefore be closed :)
