### ISSUE TITLE
Missing fields using `Convert notice to the latest SDK version` on preview

### ISSUE THREAD

**Issue by mcwnuq** [OP-TED/eForms-SDK#939]
![image](https://github.com/OP-TED/eForms-SDK/assets/11915730/d82b636a-727b-41e7-8e8e-4aeac4a499a8)
After conversion all country fields are missing.

 Before conversion:
![image](https://github.com/OP-TED/eForms-SDK/assets/11915730/7ed84306-115e-4282-b8a4-81b78b120f8f)

After conversion:
![image](https://github.com/OP-TED/eForms-SDK/assets/11915730/5faba0ce-c7ad-492f-b3e3-23c8eeb2848a)

**Comment by YvesJo** [comment]
Hi,
Could you please provide some further information like the initial version?
Thanks

**Comment by pdonohoe** [comment]
![cecf9989-b3c0-4ca9-9194-664ab4663841](https://github.com/OP-TED/eForms-SDK/assets/1267429/6211bf64-6758-459f-a22f-86dab489435f)
Google Translate translation of the CVS error image into English

**Comment by mcwnuq** [comment]
Here is my initial XML (pre converted). Initial SDK version is 1.10
https://gist.github.com/mcwnuq/b0f823ee10db69ef507df4a6147fcee4

**Comment by YvesJo** [comment]
Thanks.
After a first look at the issue, it has been clarified that this is not SDK related and you should preferably get in touch with the Helpdesk. We will also make them aware of this issue.
This concern is most likely to eNotices2 behavior. Please note that the list used for country codes validation as changed name with SDK 1.11 from "eforms-country" to "country" which could have some side effects and needs however to get confirmed.

**Comment by YvesJo** [comment]
Not an SDK issue. Helpdesk will get informed.
