### ISSUE TITLE
Missing Schematron messages

### ISSUE THREAD

**Issue by klakegg** [OP-TED/eForms-SDK#94]
The English translations are currently missing for the following Schematron validation rules:

* rule|text|BR-BT-00024-0210
* rule|text|BR-BT-00024-0207
* rule|text|BR-BT-00024-0208
* rule|text|BR-BT-00024-0209
* rule|text|BR-BT-00514-0304

**Comment by bertrand-lorentz** [comment]
Thank you for your feedback.

The English texts for those rules is indeed missing. They will be added in the next version of the SDK.

**Comment by bertrand-lorentz** [comment]
The English translations listed are included in version 1.1.0 that was just released. So I'm closing this.

**Comment by klakegg** [comment]
When are you planning to release this changes as part of version 1.0.1?
