### ISSUE TITLE
Wrong rule texts in GR-LotResult-ReceivedSubmissions

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#960]
Some rule texts within the GR-LotResult-ReceivedSubmissions group are incorrect. The rule texts refer to BTs that do not (or no longer?) exist. In englisch at least the following text is wrong: 

rule|text|BR-BT-13713-0102">If received tenders micro (BT-1481) is not empty, BT-1482 (BT-1482) is not empty and BT-1483 (BT-1483) is not empty, then BT-148 (BT-148) must be equal to the sum of BT-1481 (BT-1481), BT-1482 (BT-1482) and BT-1483 (BT-1483)

In the german translation at least the following texts refer to wrong BTs:

BR-BT-13713-0101">'Eingegangene Angebote oder Teilnahmeanträge' (BT-146) darf nicht niedriger sein als die Summe der eingegangenen unzulässigen Angebote (BT-741) und der eingegangenen nicht geprüften Angebote (BT-742)
BR-BT-13713-0102">Wenn erhaltene Angebote Mikro (BT-1481) nicht leer ist, ist BT-1482 (BT-1482) nicht leer und ist BT-1483 (BT-1483) nicht leer, dann muss BT-148 (BT-148) gleich der Summe aus BT-1481 (BT-1481), BT-1482 (BT-1482) und BT-1483 (BT-1483) sein
BR-BT-13713-0103">Angebote von KMU (BT-148) müssen niedriger oder gleich sein wie eingegangene Angebote (BT-146)</entry>
<entry key="rule|text|BR-BT-13713-0104">Erhaltene Angebote aus anderen EU-Ländern als dasjenige des Käuferwertes müssen niedriger oder gleich den eingegangenen Angeboten (BT-146) sein
BR-BT-13713-0103">Angebote von KMU (BT-148) müssen niedriger oder gleich sein wie eingegangene Angebote (BT-146)

The texts are also all attached to the field "BT-13713-LotResult". Wouldn't it be better to attach the rules directly to the GR-LotResult-ReceivedSubmissions group?

**Comment by YvesJo** [comment]
Thanks,
This issue is already known and was prepared for SDK 1.10 (https://github.com/OP-TED/eForms-SDK/discussions/532), updates were somehow lost. 
We'll fix it asap, either in SDK 1.12 or with the next labels update. This will also get applied to previous versions.

**Comment by GarrusMD** [comment]
Thanks :)

**Comment by GarrusMD** [comment]
Hi @YvesJo the german translation in SDK 1.12 still refers to BTs that no longer exist: At least in BR-BT-13713-0101, BR-BT-13713-0103, BR-BT-13713-0104, BR-BT-13713-0105 and BR-BT-13713-0106.

**Comment by YvesJo** [comment]
Hi,
The rules were expressed using Business Terms IDs and not fields IDs. rule|text|BR-BT-13713-0102 in its previous state was not understandable and has been fixed, other rules could be expressed referencing Fields IDs instead when you think this really adds value in which case this would be done for SDK 1.13.

**Comment by GarrusMD** [comment]
It would help to display the correct BTs. The correct BTs are also displayed in the English version.

**Comment by YvesJo** [comment]
Ok, I'll have a closer look at it.
I reopen that ticket and associate it to SDK 1.13 regarding the remaining rules

**Comment by GarrusMD** [comment]
@YvesJo Hi, I have noticed that, the rule texts for BR-BT-13713-0101, BR-BT-13713-0103 , BR-BT-13713-0104 and BR-BT-13713-0105. Still reference BTs (BT-148 and BT-146) that no longer exist.
